name: "CI - Test"
on:
  push:
    branches:
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        features:
          - "devtools"
        baseImage:
          - "mcr.microsoft.com/devcontainers/base:ubuntu"
          - "mcr.microsoft.com/vscode/devcontainers/base:alpine"
    steps:
      - uses: actions/checkout@v2

      - name: "Install latest devcontainer CLI"
        run: npm install -g @devcontainers/cli

      - name: "Generating tests for '${{ matrix.features }}' against '${{ matrix.baseImage }}'"
        run: devcontainer features test -f ${{ matrix.features }} -i ${{ matrix.baseImage }} .

      - name: "Validate Features"
        uses: devcontainers/action@v1
        with:
          validate-only: "true"
          publish-features: "false"
          base-path-to-features: "./src"
          generate-docs: "false"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
